/-
  Basic module — imports definitions for the impossibility theorem.
-/
import UniversalImpossibility.Defs
import UniversalImpossibility.Trilemma
import UniversalImpossibility.Iterative
import UniversalImpossibility.Lasso
import UniversalImpossibility.NeuralNet
import UniversalImpossibility.SplitGap
import UniversalImpossibility.SymmetryDerive
import UniversalImpossibility.Ratio
import UniversalImpossibility.General
import UniversalImpossibility.SpearmanDef
import UniversalImpossibility.Impossibility
import UniversalImpossibility.Corollary
import UniversalImpossibility.EnsembleBound
import UniversalImpossibility.DesignSpace
import UniversalImpossibility.DesignSpaceFull
import UniversalImpossibility.FlipRate
import UniversalImpossibility.ModelSelection
import UniversalImpossibility.ModelSelectionDesignSpace
import UniversalImpossibility.AlphaFaithful
import UniversalImpossibility.UnfaithfulBound
import UniversalImpossibility.PathConvergence
import UniversalImpossibility.RashomonUniversality
import UniversalImpossibility.RashomonInevitability
import UniversalImpossibility.LocalGlobal
import UniversalImpossibility.ConditionalImpossibility
import UniversalImpossibility.SymmetricBayes
import UniversalImpossibility.SBDInstances
import UniversalImpossibility.Efficiency
import UniversalImpossibility.CausalDiscovery
import UniversalImpossibility.FairnessAudit
import UniversalImpossibility.IntersectionalFairness
import UniversalImpossibility.Consistency
import UniversalImpossibility.GaussianFlipRate
import UniversalImpossibility.BinaryQuantizer
import UniversalImpossibility.RobustnessLipschitz
import UniversalImpossibility.MutualInformation
import UniversalImpossibility.StumpProportionality
import UniversalImpossibility.QueryComplexityParametric
import UniversalImpossibility.LocalSufficiency
import UniversalImpossibility.FIMImpossibility
import UniversalImpossibility.QueryComplexity
import UniversalImpossibility.QueryComplexityDerived
import UniversalImpossibility.Setup
import UniversalImpossibility.ApproximateEquity
import UniversalImpossibility.ProportionalityLocal
import UniversalImpossibility.Qualitative
import UniversalImpossibility.LossPreservation
import UniversalImpossibility.BayesOptimalTie
import UniversalImpossibility.ParetoOptimality
import UniversalImpossibility.ExplanationSystem
import UniversalImpossibility.AttributionInstanceConstructive  -- was AttributionInstance
import UniversalImpossibility.AttentionInstanceConstructive     -- was AttentionInstance
import UniversalImpossibility.SaliencyInstanceConstructive      -- was SaliencyInstance
import UniversalImpossibility.LLMExplanationInstanceConstructive -- was LLMExplanationInstance
import UniversalImpossibility.CounterfactualInstanceConstructive -- was CounterfactualInstance
import UniversalImpossibility.ConceptInstanceConstructive       -- was ConceptInstance
import UniversalImpossibility.CausalInstanceConstructive        -- was CausalInstance
import UniversalImpossibility.MarkovEquivalence
import UniversalImpossibility.ModelSelectionInstanceConstructive -- was ModelSelectionInstance
import UniversalImpossibility.MechInterpInstanceConstructive    -- was MechInterpInstance
import UniversalImpossibility.UniversalImpossibility
import UniversalImpossibility.UniversalResolution
import UniversalImpossibility.DASHResolution
import UniversalImpossibility.CPDAGResolution
import UniversalImpossibility.UniversalDesignSpace
import UniversalImpossibility.Ubiquity
import UniversalImpossibility.Necessity
import UniversalImpossibility.QuantitativeBound
import UniversalImpossibility.QueryRelative
import UniversalImpossibility.GeneticCode
import UniversalImpossibility.LinearSystem
import UniversalImpossibility.ViewUpdate
import UniversalImpossibility.PhaseProblem
import UniversalImpossibility.GaugeTheory
import UniversalImpossibility.SyntacticAmbiguity
import UniversalImpossibility.StatisticalMechanics
import UniversalImpossibility.AttentionInstanceConstructive
import UniversalImpossibility.ModelSelectionInstanceConstructive
import UniversalImpossibility.CounterfactualInstanceConstructive
import UniversalImpossibility.ConceptInstanceConstructive
import UniversalImpossibility.SaliencyInstanceConstructive
import UniversalImpossibility.LLMExplanationInstanceConstructive
import UniversalImpossibility.MechInterpInstanceConstructive
import UniversalImpossibility.DuhemQuine
import UniversalImpossibility.ArrowInstance
import UniversalImpossibility.QMInterpretation
import UniversalImpossibility.PeresMermin
import UniversalImpossibility.MIQuantitativeBridge
import UniversalImpossibility.UncertaintyFromSymmetry
import UniversalImpossibility.MaximalIncompatibility
import UniversalImpossibility.BilemmaCharacterization
import UniversalImpossibility.PredictiveConsequences
import UniversalImpossibility.ApproximateRashomon
import UniversalImpossibility.EnrichmentStack
import UniversalImpossibility.ValueAlignment
import UniversalImpossibility.VarianceDerivation
import UniversalImpossibility.UnfaithfulQuantitative
import UniversalImpossibility.GeneralizedBilemma
import UniversalImpossibility.AxiomSubstitution
import UniversalImpossibility.NecessityBiconditional
import UniversalImpossibility.QuantumMeasurementRevolution
import UniversalImpossibility.SimultaneityRevolution
import UniversalImpossibility.CausalExplanationSystem
import UniversalImpossibility.MeasureHypotheses
import UniversalImpossibility.RecursiveImpossibility
import UniversalImpossibility.ExplanationLandscape
import UniversalImpossibility.GoedelIncompleteness
import UniversalImpossibility.LanglandsCorrespondence
import UniversalImpossibility.MultiAnalystInstance
