/- CI axiom audit for the Tier-A spine.
   Run: lake env lean paper/scripts/CheckAxioms.lean
   The ci script asserts each spine declaration "does not depend on any axioms"
   (propext/Quot.sound/funext are Lean-core and acceptable; the assertion below
   greps only for the custom axioms gbdtWorld/gbdtAxioms and ofReduceBool). -/
import UniversalImpossibility.ExplanationSystem
import UniversalImpossibility.NecessityBiconditional
import UniversalImpossibility.MaximalIncompatibility
import UniversalImpossibility.UncertaintyFromSymmetry
import UniversalImpossibility.AttributionInstanceConstructive
import UniversalImpossibility.AttentionInstanceConstructive
import UniversalImpossibility.CounterfactualInstanceConstructive
import UniversalImpossibility.ConceptInstanceConstructive
import UniversalImpossibility.CausalInstanceConstructive
import UniversalImpossibility.ModelSelectionInstanceConstructive
import UniversalImpossibility.MechInterpInstanceConstructive
import UniversalImpossibility.SaliencyInstanceConstructive
import UniversalImpossibility.LLMExplanationInstanceConstructive
import UniversalImpossibility.MIWitness
import UniversalImpossibility.CertificateGuarantee
import UniversalImpossibility.PopulationCantelli
import UniversalImpossibility.IncompatibilityCharacterization

#print axioms explanation_impossibility
#print axioms bilemma
#print axioms rashomon_biconditional_neq
#print axioms fully_specified_possibility
#print axioms UniversalImpossibility.reynolds_image_in_fixed
#print axioms UniversalImpossibility.reynolds_best_approximation
#print axioms attribution_impossibility_constructive
#print axioms attention_impossibility_constructive
#print axioms counterfactual_impossibility_constructive
#print axioms concept_impossibility_constructive
#print axioms causal_impossibility_constructive
#print axioms model_selection_impossibility_constructive
#print axioms mech_interp_impossibility_constructive
#print axioms saliency_impossibility_constructive
#print axioms llm_explanation_impossibility_constructive
#print axioms UniversalImpossibility.MIWitness.concrete_mi_impossibility
#print axioms UniversalImpossibility.MIWitness.hdep_implies_diff
#print axioms UniversalImpossibility.Certificate.cantelli_lower_tail
#print axioms UniversalImpossibility.Certificate.flip_le_one_div_one_add_snrSq
#print axioms UniversalImpossibility.Certificate.stable_flip_le_one_fifth
#print axioms UniversalImpossibility.Certificate.simultaneous_cantelli
#print axioms UniversalImpossibility.PopulationCantelli.cantelli_upper
#print axioms UniversalImpossibility.PopulationCantelli.cantelli_lower
#print axioms UniversalImpossibility.IncompatChar.possibility_of_equiv_compat
#print axioms UniversalImpossibility.IncompatChar.rashomon_biconditional_of_equiv
#print axioms UniversalImpossibility.IncompatChar.general_boundary_fails
