/- CI axiom audit for the Tier-A spine.
   Run: lake env lean paper/scripts/CheckAxioms.lean
   The ci script asserts each spine declaration "does not depend on any axioms"
   (propext/Quot.sound/funext are Lean-core and acceptable; the assertion below
   greps only for the custom axioms gbdtWorld/gbdtAxioms and ofReduceBool). -/
import UniversalImpossibility.ExplanationSystem
import UniversalImpossibility.NecessityBiconditional
import UniversalImpossibility.MaximalIncompatibility
import UniversalImpossibility.UncertaintyFromSymmetry
import UniversalImpossibility.AttributionInstanceConstructive
import UniversalImpossibility.AttentionInstanceConstructive
import UniversalImpossibility.CounterfactualInstanceConstructive
import UniversalImpossibility.ConceptInstanceConstructive
import UniversalImpossibility.CausalInstanceConstructive
import UniversalImpossibility.ModelSelectionInstanceConstructive
import UniversalImpossibility.MechInterpInstanceConstructive
import UniversalImpossibility.SaliencyInstanceConstructive
import UniversalImpossibility.LLMExplanationInstanceConstructive
import UniversalImpossibility.MIWitness
import UniversalImpossibility.CertificateGuarantee
import UniversalImpossibility.PopulationCantelli
import UniversalImpossibility.IncompatibilityCharacterization
import UniversalImpossibility.GaussMarkovDASH
import UniversalImpossibility.DavisKahanSinTheta
import UniversalImpossibility.CertificateTight
import UniversalImpossibility.Dichotomy
import UniversalImpossibility.TransferTheorem
import UniversalImpossibility.MolienCapacity
import UniversalImpossibility.CapacityFunctoriality
import UniversalImpossibility.TransferGeneral
import UniversalImpossibility.StructureTheorem
import UniversalImpossibility.HomogeneousFinite
import UniversalImpossibility.GradedMolien
import UniversalImpossibility.UbiquityDimensional

#print axioms explanation_impossibility
#print axioms bilemma
#print axioms rashomon_biconditional_neq
#print axioms fully_specified_possibility
#print axioms UniversalImpossibility.reynolds_image_in_fixed
#print axioms UniversalImpossibility.Certificate.flip_bound_tight
#print axioms UniversalImpossibility.Certificate.flip_zero_at_low_snr
#print axioms Dichotomy.orbit_subset_rashomon
#print axioms Dichotomy.rashomon_within_tube
#print axioms Dichotomy.dichotomy
#print axioms UniversalImpossibility.Transfer.transfer_flip_bound
#print axioms UniversalImpossibility.Transfer.transfer_flipFreq_bound
#print axioms UniversalImpossibility.Molien.capacity_reynolds_eq_char_average
#print axioms UniversalImpossibility.Molien.capacity_reynolds_eq_finrank_invariants
#print axioms UniversalImpossibility.Capacity.structural_floor_dim
#print axioms UniversalImpossibility.Capacity.capacity_antitone_subgroup
#print axioms UniversalImpossibility.Transfer.transfer_flip_general
#print axioms stable_iff_gInvariant
#print axioms UniversalImpossibility.Capacity.explanation_structure_theorem
#print axioms UniversalImpossibility.Graded.homogeneousSubmodule_finiteDimensional
#print axioms UniversalImpossibility.Graded.graded_molien_char_average
#print axioms UniversalImpossibility.Ubiquity.exists_observational_collision
#print axioms UniversalImpossibility.Ubiquity.fderiv_exists_kernel_direction
#print axioms UniversalImpossibility.Ubiquity.underspecified_impossibility
#print axioms UniversalImpossibility.Ubiquity.regular_fiber_not_isolated
#print axioms UniversalImpossibility.Ubiquity.smooth_regular_underspecified_impossibility
#print axioms UniversalImpossibility.Ubiquity.regular_value_fiber_not_isolated
#print axioms UniversalImpossibility.Ubiquity.generic_ubiquity_of_sard
#print axioms UniversalImpossibility.Ubiquity.sardProperty_of_continuousLinearMap
#print axioms UniversalImpossibility.reynolds_best_approximation
#print axioms attribution_impossibility_constructive
#print axioms attention_impossibility_constructive
#print axioms counterfactual_impossibility_constructive
#print axioms concept_impossibility_constructive
#print axioms causal_impossibility_constructive
#print axioms model_selection_impossibility_constructive
#print axioms mech_interp_impossibility_constructive
#print axioms saliency_impossibility_constructive
#print axioms llm_explanation_impossibility_constructive
#print axioms UniversalImpossibility.MIWitness.concrete_mi_impossibility
#print axioms UniversalImpossibility.MIWitness.hdep_implies_diff
#print axioms UniversalImpossibility.Certificate.cantelli_lower_tail
#print axioms UniversalImpossibility.Certificate.flip_le_one_div_one_add_snrSq
#print axioms UniversalImpossibility.Certificate.stable_flip_le_one_fifth
#print axioms UniversalImpossibility.Certificate.simultaneous_cantelli
#print axioms UniversalImpossibility.PopulationCantelli.cantelli_upper
#print axioms UniversalImpossibility.PopulationCantelli.cantelli_lower
#print axioms UniversalImpossibility.IncompatChar.possibility_of_equiv_compat
#print axioms UniversalImpossibility.IncompatChar.rashomon_biconditional_of_equiv
#print axioms UniversalImpossibility.IncompatChar.general_boundary_fails
#print axioms UniversalImpossibility.GaussMarkovDASH.dash_min_variance
#print axioms UniversalImpossibility.GaussMarkovDASH.dash_orbit_average_optimal
#print axioms UniversalImpossibility.DavisKahanSinTheta.gapped_sylvester_frobenius
#print axioms UniversalImpossibility.DavisKahanSinTheta.davisKahan_sinTheta_hermitian
