#!/usr/bin/env python3
"""Generate paper/claims.tex — the single source of truth for every repo-derived
count cited in the monograph and venue drafts.

Counts are computed from the actual Lean sources of the three repositories.
NEVER hand-edit claims.tex; rerun this script. CI fails if claims.tex is stale.

Conventions (match repo CLAUDE.md):
  theorems+lemmas : grep ^theorem|^lemma  (declaration lines)
  axioms          : grep '^axiom '        (trailing space — bare ^axiom
                    overcounts doc-comment lines starting with "axioms…")
  native_decide   : tactic uses only (standalone line or 'by native_decide'),
                    not docstring mentions
"""
import re, subprocess, sys, datetime
from pathlib import Path

HERE = Path(__file__).resolve()
MAIN = HERE.parents[2]
DASH = MAIN.parent / "dash-impossibility-lean"
OSTR = MAIN.parent / "ostrowski-impossibility"
OUT = MAIN / "paper" / "claims.tex"

REPOS = {
    "Main": (MAIN, MAIN / "UniversalImpossibility", False),
    "Dash": (DASH, DASH / "DASHImpossibility", False),
    "Ostrowski": (OSTR, OSTR / "OstrowskiImpossibility", True),
}

THM = re.compile(r"^(theorem|lemma) ", re.M)
AX = re.compile(r"^axiom ", re.M)
ND = re.compile(r"(^\s*native_decide\s*$)|(by native_decide)", re.M)
NAME = re.compile(r"^(?:theorem|lemma) ([A-Za-z0-9_']+)", re.M)


def lean_files(root: Path, recursive: bool):
    return sorted(root.rglob("*.lean") if recursive else root.glob("*.lean"))


def commit(repo: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        return "unknown"


stats, names = {}, {}
for label, (repo, root, rec) in REPOS.items():
    files = lean_files(root, rec)
    text = "".join(f.read_text() for f in files)
    stats[label] = {
        "Files": len(files),
        "Theorems": len(THM.findall(text)),
        "Axioms": len(AX.findall(text)),
        "NativeDecide": len(ND.findall(text)),
        "Sorry": sum(
            1 for f in files for line in f.read_text().splitlines()
            if re.match(r"^\s*sorry\s*$", line)
        ),
        "Commit": commit(repo),
    }
    names[label] = set(NAME.findall(text))

ov_dash = len(names["Dash"] & names["Main"])
ov_ostr = len(names["Ostrowski"] & names["Main"])
pct_dash = round(100 * ov_dash / len(names["Dash"]))
pct_ostr = round(100 * ov_ostr / len(names["Ostrowski"]))
distinct = len(names["Main"] | names["Dash"] | names["Ostrowski"])

for label, s in stats.items():
    assert s["Sorry"] == 0, f"{label} has sorry lines!"

lines = [
    "% AUTO-GENERATED by paper/scripts/gen_claims.py — DO NOT EDIT.",
    f"% Generated {datetime.date.today().isoformat()} from commits "
    f"main:{stats['Main']['Commit']} dash:{stats['Dash']['Commit']} "
    f"ostrowski:{stats['Ostrowski']['Commit']}",
]
for label, s in stats.items():
    for k in ("Files", "Theorems", "Axioms", "NativeDecide"):
        lines.append(rf"\newcommand{{\Claim{label}{k}}}{{{s[k]}}}")
lines += [
    rf"\newcommand{{\ClaimOverlapDashPct}}{{{pct_dash}}}",
    rf"\newcommand{{\ClaimOverlapOstrowskiPct}}{{{pct_ostr}}}",
    rf"\newcommand{{\ClaimDistinctTheorems}}{{{distinct}}}",
    rf"\newcommand{{\ClaimTotalAxioms}}{{{sum(s['Axioms'] for s in stats.values())}}}",
    rf"\newcommand{{\ClaimTotalNativeDecide}}{{{sum(s['NativeDecide'] for s in stats.values())}}}",
]
new = "\n".join(lines) + "\n"

if "--check" in sys.argv:
    old = OUT.read_text() if OUT.exists() else ""
    # ignore the dated comment lines when checking freshness
    strip = lambda t: "\n".join(l for l in t.splitlines() if not l.startswith("%"))
    if strip(old) != strip(new):
        print("STALE: claims.tex does not match repo state. Rerun gen_claims.py")
        sys.exit(1)
    print("claims.tex up to date")
else:
    OUT.write_text(new)
    print(f"wrote {OUT}")
    for label, s in stats.items():
        print(f"  {label}: {s}")
    print(f"  overlap dash {pct_dash}% ostrowski {pct_ostr}% distinct {distinct}")
