"""Regenerate all figures with publication-quality formatting.

Applies publication_style.mplstyle for consistent Type 1 fonts (Computer Modern),
proper sizing for JMLR column/text widths, and clean aesthetics.

Usage: python3 paper/scripts/regenerate_all_figures.py
"""
import os
import sys
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PAPER_DIR = os.path.dirname(SCRIPT_DIR)
REPO_DIR = os.path.dirname(PAPER_DIR)
STYLE_FILE = os.path.join(SCRIPT_DIR, "publication_style.mplstyle")

# Map: figure filename -> generating script
FIGURE_SCRIPTS = {
    # Main figures (generated by generate_figures.py)
    "ratio_divergence.pdf": "generate_figures.py",
    "shap_instability.pdf": "generate_figures.py",
    "dash_resolution.pdf": "generate_figures.py",
    # Individual scripts
    "design_space.pdf": "design_space_figure.py",
    "snr_calibration.pdf": "snr_calibration.py",
    "real_world_instability.pdf": "real_world_validation.py",
    "comprehensive_f1.pdf": "comprehensive_validation.py",
    "conditional_threshold.pdf": "conditional_shap_threshold.py",
    "f1_f5_diagnostic.pdf": "f1_f5_validation.py",
    "information_loss.pdf": "information_loss.py",
    "alpha_precision.pdf": "alpha_precision_validation.py",
    # trilemma.pdf is TikZ-generated, skip
}

def apply_style():
    """Apply publication style globally before any figure generation."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.style.use(STYLE_FILE)
    # Ensure Type 1 fonts
    matplotlib.rcParams['pdf.fonttype'] = 42
    matplotlib.rcParams['ps.fonttype'] = 42

def check_latex():
    """Check if LaTeX is available for text.usetex."""
    try:
        result = subprocess.run(['latex', '--version'], capture_output=True, timeout=5)
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False

def main():
    os.chdir(REPO_DIR)

    if not check_latex():
        print("WARNING: LaTeX not found. Falling back to mathtext (no text.usetex).")
        # Modify style to not use usetex
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        plt.style.use(STYLE_FILE)
        matplotlib.rcParams['text.usetex'] = False
        matplotlib.rcParams['pdf.fonttype'] = 42
        matplotlib.rcParams['ps.fonttype'] = 42
    else:
        apply_style()

    # Regenerate figures by running their scripts
    # Each script saves to paper/figures/ automatically
    unique_scripts = sorted(set(FIGURE_SCRIPTS.values()))

    for script_name in unique_scripts:
        script_path = os.path.join(SCRIPT_DIR, script_name)
        if not os.path.exists(script_path):
            print(f"SKIP: {script_name} (not found)")
            continue

        print(f"Regenerating via {script_name}...")
        try:
            result = subprocess.run(
                [sys.executable, script_path],
                capture_output=True, text=True, timeout=300,
                env={**os.environ, 'MPLSTYLE': STYLE_FILE}
            )
            if result.returncode == 0:
                print(f"  OK: {script_name}")
            else:
                # Many scripts fail due to missing data/packages but
                # still generate figures before failing
                stderr_short = result.stderr[-200:] if result.stderr else ""
                print(f"  WARN: {script_name} exited {result.returncode}")
                if stderr_short:
                    print(f"  {stderr_short}")
        except subprocess.TimeoutExpired:
            print(f"  TIMEOUT: {script_name} (>300s)")
        except Exception as e:
            print(f"  ERROR: {script_name}: {e}")

    # Verify fonts
    print("\n=== Font verification ===")
    for fig_name in sorted(FIGURE_SCRIPTS.keys()):
        fig_path = os.path.join(PAPER_DIR, "figures", fig_name)
        if os.path.exists(fig_path):
            result = subprocess.run(
                ['pdffonts', fig_path],
                capture_output=True, text=True
            )
            type3 = [l for l in result.stdout.split('\n') if 'Type 3' in l]
            if type3:
                print(f"  WARNING Type 3 fonts: {fig_name}")
                for l in type3:
                    print(f"    {l.strip()}")
            else:
                print(f"  OK: {fig_name}")
        else:
            print(f"  MISSING: {fig_name}")

if __name__ == "__main__":
    main()
